# Generated by cucumber-sinatra. (2015-09-25 20:48:24 +0300)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/watch_counter.rb')

WatchCounter.config = WatchCounter::Config.new(
  storage: WatchCounter::SqliteMemoryStorage,
  bind: 'localhost',
  port: '4567'
)
WatchCounter.app

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = WatchCounter::HttpServer

class WatchCounter::HttpServerWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
  include Rack::Test::Methods

  def app
    Capybara.app
  end
end

World do
  WatchCounter::HttpServerWorld.new
end
